### ISSUE TITLE
Unexpected server response (0) while retrieving PDF

### ISSUE THREAD

**Issue by ItsJoeTurner** [shyammohankanojia/pdfjs_rails#3]
I'm seeing this error after uploading PDFs to Amazon S3 w/ Paperclip. The PDF is there, and I'm able to access it fine by putting the URL into the address bar, but PDF.js just doesn't like it?

`Unexpected server response (0) while retrieving PDF`

**Comment by SnezanaDichevska** [comment]
also having the same problem, any solutions ? @ItsJoeTurner
